In [26]:
import numpy as np

In [27]:
## simulate data

# simulation parameters
N = 1000  # time points
M =    4  # channels

# time vector (radian units)
t = np.linspace(0,6*np.pi,N)

# relationship across channels (imposing covariance)
chanrel = np.sin(np.linspace(0,2*np.pi,M))

# create the data
data = np.zeros((M,N))
for mi in range(M):
    data[mi:] = np.sin(t) * chanrel[mi]

data = data + np.random.randn(M,N)

dataCovMat = np.cov(data)
dataCorrMat = np.corrcoef(data)

In [28]:
stdDiag = np.diag(np.std(data, axis=1))
stdDiag

array([[0.97632209, 0.        , 0.        , 0.        ],
       [0.        , 1.16674915, 0.        , 0.        ],
       [0.        , 0.        , 1.16802766, 0.        ],
       [0.        , 0.        , 0.        , 0.95530474]])

In [29]:
np.matmul(np.matmul(stdDiag, dataCorrMat), stdDiag)

array([[ 0.95320482,  0.00287548,  0.02075392, -0.0095326 ],
       [ 0.00287548,  1.36130359, -0.3668193 , -0.01608269],
       [ 0.02075392, -0.3668193 ,  1.36428862, -0.0072109 ],
       [-0.0095326 , -0.01608269, -0.0072109 ,  0.91260715]])

In [30]:
dataCovMat

array([[ 0.95415898,  0.00287836,  0.0207747 , -0.00954214],
       [ 0.00287836,  1.36266625, -0.36718649, -0.01609879],
       [ 0.0207747 , -0.36718649,  1.36565427, -0.00721812],
       [-0.00954214, -0.01609879, -0.00721812,  0.91352067]])

In [31]:
stdDiagInv = np.linalg.inv(stdDiag)
np.matmul(np.matmul(stdDiagInv, dataCovMat), stdDiagInv)

array([[ 1.001001  ,  0.00252682,  0.01821749, -0.01023083],
       [ 0.00252682,  1.001001  , -0.26943627, -0.01444354],
       [ 0.01821749, -0.26943627,  1.001001  , -0.00646888],
       [-0.01023083, -0.01444354, -0.00646888,  1.001001  ]])

In [32]:
dataCorrMat

array([[ 1.        ,  0.00252429,  0.01819927, -0.0102206 ],
       [ 0.00252429,  1.        , -0.26916684, -0.0144291 ],
       [ 0.01819927, -0.26916684,  1.        , -0.00646241],
       [-0.0102206 , -0.0144291 , -0.00646241,  1.        ]])